os:
  - linux
  - osx
language: rust
sudo: false
matrix:
  fast_finish: true
  include:
  - rust: nightly
    env: FEATURES="--features nightly"
  - rust: stable
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
cache:
  apt: true
  directories:
    - target/debug/deps
    - target/debug/build
notifications:
  email:
    on_success: never
    on_failure: never
branches:
  only:
    - master
    - develop
script:
  - |
      cargo test --lib &&
      cargo test --release --lib
before_script:
  - |
    export PATH=$HOME/.local/bin:$PATH
after_success:
  - |
    wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
    tar xzf master.tar.gz && mkdir kcov-master/build && cd kcov-master/build &&
    cmake -DCMAKE_INSTALL_PREFIX:PATH=../release .. && make &&
    make install && cd ../.. &&
    kcov-master/release/bin/kcov --verify \
      --coveralls-id=$TRAVIS_JOB_ID \
      --exclude-pattern=/.cargo \
      target/kcov target/debug/spork-*
env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""