os:
  - linux
  - osx
language: rust
sudo: false
matrix:
  fast_finish: true
  include:
  - rust: nightly
    env: FEATURES="--features nightly"
  - rust: beta
  - rust: stable
addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - binutils-dev
cache:
  apt: true
  directories:
    - target/debug/deps
    - target/debug/build
notifications:
  email:
    on_success: never
    on_failure: never
branches:
  only:
    - master
    - develop
script:
  - |
      travis-cargo build &&
      travis-cargo test -- --lib &&
      travis-cargo --only stable doc
before_script:
  - |
    pip install 'travis-cargo<0.2' --user &&
    export PATH=`python -m site --user-base`/bin:$PATH
    #export PATH=$HOME/.local/bin:$PATH
after_success:
  - travis-cargo --only stable doc-upload
  - |
    wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
    tar xzf master.tar.gz && mkdir kcov-master/build && cd kcov-master/build &&
    cmake -DCMAKE_INSTALL_PREFIX:PATH=../release .. && make &&
    make install && cd ../.. &&
    kcov-master/release/bin/kcov --verify \
      --coveralls-id=$TRAVIS_JOB_ID \
      --exclude-pattern=/.cargo \
      target/kcov target/debug/spork-*
env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
    - secure: "WhneJiJXf9m/ewJM+DJLK/JrFrrVwsO45ai2r9uYnQRK0pXcUtOW/KN0qmvRNoMIyn7aM8/k8FozLaPIu6vuunvvsxSVCpX9EvRPkx9MZn/AcuFwf14rfzk895udED2U6eptaZAX+vvUpdV7GTqdWq/f1VaZm2DcNsj8BCvsLP8HdzHq8Jt4cVo/yIDLKm5ecNsIxjoQqHQWoTNrO+10S06y03vp49jugJL+78UxZ7PQOcn1d4t1SdUcVdRSVqh7SaVUsHurWYfEFIO6yCuUIkagn1o5h6OZvpKFcN6Z1MACdb1H1w6pvDopPwJOCc72WXkh1i3m+uk3wpID4ycjqhYTLI2sEOSnYf+3oUGR89Kw4UwDUgU6eechTxss5L3K8+1YtnmUdf96OSi0fhh8pz/7e5MlO7dUvjXjlywut4kml1xreISafurptOEw/EzEWpGoVO168h5103BZ1rK9jZDOixzTX0I8TKsjCBZpuFHYWXTu/8Xbz5BeRftX4rSwbLwngzvE9sHzfOciOtofTlu9q0ME1PnIsxykQ34Mt0ksABTSWpXpbCT25eocr0ztuvDNhHMIVZDdFaiRSTu39hN6MgrRgKJVlCI0utA+KENL/KeLIBsLHZHiBmfreNNrAchrMONl6nwNXoCQUhvNbTIjjKcapyjD26k83EQ0jSU="
