[package]
authors = ["Alec Embke <aembke@gmail.com>"]
categories = []
documentation = "http://azuqua.github.io/spork.rs"
keywords = ["cpu", "memory", "usage"]
license = "MIT"
name = "spork"
readme = "README.md"
repository = "https://github.com/azuqua/spork.rs"
version = "0.1.0"

[dependencies]
chrono = "0.3"
kernel32-sys = "0.2"
libc = "0.2"
psapi-sys = "0.1"
sys-info = "0.5.6"
thread-id = "3.0"
winapi = "0.2"

[dependencies.mach]
git = "https://github.com/azuqua/mach"

[dev-dependencies]
rand = "0.3.15"

[features]
compile_unimplemented = []
default = []

[lib]
doctest = false
